name: Build My Angular App

on:
  push:
    branches: [ main ]

jobs:
  build-angular-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.1
      - name: setup Node JS
        uses: Drafteame/node-cache-action@v0.3.0
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install

      - name: Run Angular build
        run: npm run build 

      
